version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: flaskdb
      MYSQL_USER: app_user
      MYSQL_PASSWORD: appMate123
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: